DROP VIEW OLDMEN;
DROP VIEW FIREDEMPS;
DROP VIEW Sotrudnik_3_kv;
DROP VIEW FIREDEMPS_2;

CREATE VIEW OLDMEN AS 
SELECT * FROM EMP 
WHERE (MONTHS_BETWEEN(SYSDATE, BIRTHDATE) / 12) >= 65;

SELECT * FROM OLDMEN;

CREATE VIEW FIREDEMPS AS 
SELECT EMPNAME, ENDDATE, DEPTNAME, JOBNAME, EMPNO FROM EMP 
NATURAL JOIN CAREER 
NATURAL JOIN DEPT 
NATURAL JOIN JOB 
WHERE ENDDATE IS NOT NULL;

SELECT * FROM FIREDEMPS;

CREATE VIEW Sotrudnik_3_kv (Sotrudnik, Dolzhnost, Itogo_3_kv) AS 
SELECT EMPNAME, JOBNAME, SUM(SALVALUE) 
FROM EMP 
NATURAL JOIN JOB 
NATURAL JOIN CAREER 
NATURAL JOIN SALARY 
WHERE YEAR = 2010 AND MONTH BETWEEN 7 AND 9 AND ENDDATE IS NOT NULL 
GROUP BY EMPNAME, JOBNAME;

SELECT * FROM Sotrudnik_3_kv;

CREATE VIEW FIREDEMPS_2 AS 
SELECT EMPNAME, ENDDATE, DEPTNAME, JOBNAME, MONTH || ', ' || SALVALUE AS MONTH_TO_SUM 
FROM FIREDEMPS 
NATURAL JOIN SALARY 
WHERE EMPNO in (SELECT EMPNO 
                FROM SALARY
                GROUP BY EMPNO 
                HAVING COUNT(*) > 2) AND YEAR < EXTRACT(YEAR FROM ENDDATE);
                
SELECT * FROM FIREDEMPS_2;